### ISSUE TITLE
when will the code be released?

### ISSUE THREAD

**Issue by xiao2mo** [CVMI-Lab/Point-UV-Diffusion#1]
Thanks for ur great work!
Could u release the code and model for us to try to use it in design process?
Many thanks!

**Comment by nukadelic** [comment]
+1

**Comment by purpleman-ljl** [comment]
+1

**Comment by wqdong8** [comment]
+1

**Comment by XinYu-Andy** [comment]
I appreciate your interest. Due to previous ICLR submissions and participation in ICCV, I haven't had a chance to organize the code and data. The code will be released within the next 24 hours.

**Comment by XinYu-Andy** [comment]
Thank you for your patience, I have uploaded the code.
