### ISSUE TITLE
data preprocessing code

### ISSUE THREAD

**Issue by caojiehui** [CVMI-Lab/Point-UV-Diffusion#11]
Hello, can you share the data preprocessing code? Particularly interested in the generation of .pt data in the 'clip_img_data' and the data generation within the 'uv_model_512' folder.

**Comment by XinYu-Andy** [comment]
> Hello, can you share the data preprocessing code? Particularly interested in the generation of .pt data in the 'clip_img_data' and the data generation within the 'uv_model_512' folder.

Hi, please refer to this [issue](https://github.com/CVMI-Lab/Point-UV-Diffusion/issues/8#issuecomment-1803979812)

**Comment by caojiehui** [comment]
***@***.***上么？





在 2023-11-09 23:52:49，"Andy" ***@***.***> 写道：

Hello, can you share the data preprocessing code? Particularly interested in the generation of .pt data in the 'clip_img_data' and the data generation within the 'uv_model_512' folder.

Hi, please refer to this issue

**Comment by XinYu-Andy** [comment]
Please check the updated README
