### ISSUE TITLE
NVDiffrast - same as original repository or modified?

### ISSUE THREAD

**Issue by chibi03** [CVMI-Lab/Point-UV-Diffusion#13]
Hello,
is the differential renderer nvdiffrast the same as in the original repository (https://github.com/NVlabs/nvdiffrast) or did you customize it?
Thank you!

**Comment by XinYu-Andy** [comment]
> Hello, is the differential renderer nvdiffrast the same as in the original repository (https://github.com/NVlabs/nvdiffrast) or did you customize it? Thank you!

It is the same as the original repository.
