### ISSUE TITLE
About "vb" loss

### ISSUE THREAD

**Issue by XiangyuSu611** [CVMI-Lab/Point-UV-Diffusion#14]
Hi,

Why do you need an additional "[vb](https://github.com/CVMI-Lab/Point-UV-Diffusion/blob/d8c0e60eb8589cd755e81b391205ecded9be16e1/src/models/framework/coarse_stage/openai_diffusion/diffusion/gaussian_diffusion.py#L734)" loss?  and what is its primary function?

Thank you!

**Comment by XinYu-Andy** [comment]
> Hi,
> 
> Why you need an additional "[vb](https://github.com/CVMI-Lab/Point-UV-Diffusion/blob/d8c0e60eb8589cd755e81b391205ecded9be16e1/src/models/framework/coarse_stage/openai_diffusion/diffusion/gaussian_diffusion.py#L734)" loss? and what is its primary function?
> 
> Thank you!

Please refer to this [paper](http://arxiv.org/abs/2102.09672). It is used for optimizing the variance term.

**Comment by XiangyuSu611** [comment]
Thank you for your quickly reply :) !
