### ISSUE TITLE
[F glutil.cpp:332] eglGetDisplay() failed

### ISSUE THREAD

**Issue by XiangyuSu611** [CVMI-Lab/Point-UV-Diffusion#2]
Hi,

Thank you for sharing this great work!

I encountered an issue when running the fine stage using the provided code [test.sh](http://test.sh/) while testing the pre-trained model.

![image](https://github.com/CVMI-Lab/Point-UV-Diffusion/assets/34934357/27315174-e561-4047-a5fa-839c00580e35)

I have followed your guidance to build the Python runtime environment, and this code is running on a headless remote server with Ubuntu 20.04. Do you have any suggestions on how to solve this problem?

Thank you!

**Comment by XinYu-Andy** [comment]
> Hi,
> 
> Thank you for sharing this great work!
> 
> I encountered an issue when running the fine stage using the provided code [test.sh](http://test.sh/) while testing the pre-trained model.
> 
> ![image](https://user-images.githubusercontent.com/34934357/275686537-27315174-e561-4047-a5fa-839c00580e35.png)
> 
> I have followed your guidance to build the Python runtime environment, and this code is running on a headless remote server with Ubuntu 20.04. Do you have any suggestions on how to solve this problem?
> 
> Thank you!

This seems to be an issue related to `nvdiffrast` (https://github.com/NVlabs/nvdiffrast). I suggest first trying `cd geometry_tools/nvdiffrast` followed by `python install .`. If that doesn't work, please check their repository for any relevant information.

**Comment by XiangyuSu611** [comment]
`python install .` and change `self.ctx = dr.RasterizeContext(device=self.device)` to `self.ctx = dr.RasterizeCudaContext(device=self.device)`  in `fine_stage/render_diffusion.py`work for me.

This issue will be closed soon.
