### ISSUE TITLE
Code or method for pre-process data

### ISSUE THREAD

**Issue by XiangyuSu611** [CVMI-Lab/Point-UV-Diffusion#6]
Hi, I'm running this code on new data but get some troubles to pre-process data.

Could you please realease the code or roughly descript this method (tools) to pre-process training data in uv_model_512? 

![image](https://github.com/CVMI-Lab/Point-UV-Diffusion/assets/34934357/2cd86862-33cf-488d-b6d2-f3ec00a39756)

**Comment by XinYu-Andy** [comment]
> Hi, I'm running this code on new data but get some troubles to pre-process data.
> 
> Could you please realease the code or roughly descript this method (tools) to pre-process training data in uv_model_512?
> 
> ![image](https://user-images.githubusercontent.com/34934357/277338045-2cd86862-33cf-488d-b6d2-f3ec00a39756.png)

I haven't had the chance to clean up the data preprocessing code yet, but maybe I can share a version with you via email in the next few days.

**Comment by XiangyuSu611** [comment]
OK 👍, thank you so much!
