### ISSUE TITLE
需要使用什么硬件训练呢，有什么算力要求

### ISSUE THREAD

**Issue by DoingNow20** [CVMI-Lab/Point-UV-Diffusion#8]

**Comment by XinYu-Andy** [comment]
For each model, we trained it on four 3090 GPUs. Testing can be conducted on a single card.

**Comment by DoingNow20** [comment]
Dear Andy，

I hope this letter finds you well. Firstly, I would like to express my gratitude for your prompt response.&nbsp;

While conducting the individual testing, I have encountered some difficulties . In light of this, I would like to request your assistance in providing the code for the pre-processing data. Having access to this code would greatly facilitate my progress and enable me to overcome the current obstacles.

I understand that your time is valuable, and I truly appreciate any help you can provide. Once again, thank you for your support and understanding.

Looking forward to your positive response.

Sincerely,

DoingNow20

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Oct 31, 2023 11:34 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [CVMI-Lab/Point-UV-Diffusion] 需要使用什么硬件训练呢，有什么算力要求 (Issue #8)

&nbsp;



 
For each model, we trained it on four 3090 GPUs. Testing can be conducted on a single card.

**Comment by XinYu-Andy** [comment]
> Dear Andy， I hope this letter finds you well. Firstly, I would like to express my gratitude for your prompt response.&nbsp; While conducting the individual testing, I have encountered some difficulties . In light of this, I would like to request your assistance in providing the code for the pre-processing data. Having access to this code would greatly facilitate my progress and enable me to overcome the current obstacles. I understand that your time is valuable, and I truly appreciate any help you can provide. Once again, thank you for your support and understanding. Looking forward to your positive response. Sincerely, DoingNow20 &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: &nbsp;Tue, Oct 31, 2023 11:34 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: &nbsp;Re: [CVMI-Lab/Point-UV-Diffusion] 需要使用什么硬件训练呢，有什么算力要求 (Issue #8) &nbsp; For each model, we trained it on four 3090 GPUs. Testing can be conducted on a single card. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Which pre-processing code do you need? I can email you an unclean code.

**Comment by DoingNow20** [comment]
For example, let's consider training data for pre-processing the uv_model_512.Thank you very much！

**Comment by XinYu-Andy** [comment]
> For example, let's consider training data for pre-processing the uv_model_512.Thank you very much！

Please provide me with your email address

**Comment by DoingNow20** [comment]
Thinknight_edu@163.com

**Comment by XinYu-Andy** [comment]
> [Thinknight_edu@163.com](mailto:Thinknight_edu@163.com)

Please check your email

**Comment by peibinchen** [comment]
@XinYu-Andy Hello, could you please share me the preprocessing code? It would be very helpful! My email is 1198960858@qq.com.
Thanks.

**Comment by XinYu-Andy** [comment]
> @XinYu-Andy Hello, could you please share me the preprocessing code? It would be very helpful! My email is [1198960858@qq.com](mailto:1198960858@qq.com). Thanks.

Please check your email

**Comment by ansh941** [comment]
Dear @XinYu-Andy ,

It is a very nice work, so I hope to test my custom data using your research.
Could you please share the data preprocessing code to me?
My email is ansh941@rebuilderai.com.
Thank you.

**Comment by XinYu-Andy** [comment]
> Dear @XinYu-Andy ,
> 
> It is a very nice work, so I hope to test my custom data using your research. Could you please share the data preprocessing code to me? My email is [ansh941@rebuilderai.com](mailto:ansh941@rebuilderai.com). Thank you.

Please check your email

**Comment by HughLio** [comment]
@XinYu-Andy  Hello, thanks for the great work, Could you please share the data preprocessing code to me? my email is hughldx@126.com. Thank you.

**Comment by XinYu-Andy** [comment]
> @XinYu-Andy Hello, thanks for the great work, Could you please share the data preprocessing code to me? my email is [hughldx@126.com](mailto:hughldx@126.com). Thank you.

Please check the updated README

**Comment by zz901** [comment]
@XinYu-Andy Hello,It is a great work,Could you please share the data preprocessing code to me?My email is service1396019297@gmail.com ,Thank you

**Comment by Quieter2018** [comment]
Hi, It is really a great work, and could you please share me the data preprocessing code? I want test my own data.
My email is [quieter_0602@163.com](mailto:quieter_0602@163.com).
Thank you so much!

**Comment by XinYu-Andy** [comment]
> Hi, It is really a great work, and could you please share me the data preprocessing code? I want test my own data. My email is [quieter_0602@163.com](mailto:quieter_0602@163.com). Thank you so much!

Please check the updated README
